# Generated by Django 5.1.3 on 2024-12-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims_app", "0003_book_lib_delete_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="jurnal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("dokumen", models.FileField(upload_to="jurnal/")),
            ],
        ),
    ]
