# Generated by Django 5.1.3 on 2024-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims_app", "0007_borrowhistory_is_returned"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100, verbose_name="Nama")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("isi_pesan", models.TextField(verbose_name="Isi Pesan")),
            ],
        ),
    ]
